version: '2'

services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=codechallenge
      - POSTGRES_USER=codechallengeapp
      - POSTGRES_PASSWORD=codechallengepassword
    networks:
      - codechallenge

  app-server:
    image: codechallenge:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codechallenge
    networks:
      - codechallenge

networks:
  codechallenge:
    external: false
