name: Build and push docker image

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker images using cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: jowko
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        image_name: codechallenge
        image_tag: latest,${{github.event.number}}
        pull_image_and_stages: false
